### ISSUE TITLE
ODBP: endpoints voor robots.txt, sitemap index en DiWoo-sitemap

### ISSUE THREAD

**Issue by felixcicatt** [GPP-Woo/GPP-burgerportaal#21]
**Description (why)**
uit PSA: 

> Deelnemende gemeenten willen dat het generieke publicatieplatform wordt aangesloten op de landelijke Woo-index, zodat zij voldoen aan de wet en burgers ook via open.overheid.nl op zoek kunnen gaan naar relevante overheidsinformatie. 
> 
> Hiervoor zal de gebruikersinterface “Zoeken en Raadplegen” voorzien moeten worden van een sitemap, conform de landelijk vastgestelde specificaties. Op het moment van schrijven wordt de Woo-index nog getest in zogenaamde referentie-trajecten en kan niet uitgesloten worden dat de technische eisen nog gaan wijzigen.

**Acceptance criteria (what)**

Zie [landelijke documentatie](https://[standaarden.overheid.nl](https://standaarden.overheid.nl/diwoo/metadata)/diwoo/metadata).

- Onder de root staat een robots.txt met een verwijzing naar de DiWoo-sitemapindex. 
- De sitemapindex verwijst naar een DiWoo-sitemap.
- De sitemap voldoet aan de [DiWoo-XSD](https://[standaarden.overheid.nl](https://standaarden.overheid.nl/diwoo/metadata/diwoo-metadata-xsd)/diwoo/metadata/diwoo-metadata-xsd).
- In de sitemap worden alle documenten opgenomen:
  - mits zij de `publicatiestatus` "gepubliceerd" hebben, [ODRC#49](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/49)
  - mits zij gekoppeld zijn aan een publicatie met de `publicatiestatus` gepubliceerd, [ODRC#49](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/49)
  - zij omvat de verplichte attributen (zie [voorbeeld-xml](https://standaarden.overheid.nl/diwoo/metadata/0.9.4/xml/sitemap-alleenverplicht.xml)):
    - `loc` (URL waar het bestand van buiten te benaderen is)
    - `publisher` (op te halen bij de gekoppelde publicatie) [ODRC #66](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/66) [ODPC #64](https://github.com/GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component/issues/64)
    - `officieleTitel` (staat vastgelegd op het document) [ODRC #19](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/19) [ODPC #42](https://github.com/GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component/issues/42)
    - `informatiecategorie` (op te halen bij de gekoppelde publicatie, kan meer dan één zijn) [ODRC #48](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/48) [ODPC #47](https://github.com/GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component/issues/47)
    - `documenthandeling` (staat vastgelegd op het document, kan meer dan één zijn) [ODRC #76](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/76) [ODPC #26](https://github.com/GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component/issues/26)
    - zij omvat eveneens per document een attribuut `lastmod` [ODRC #77](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/77)
      - Let op! De wijziging van een publicatie kan betekenen dat ook de metadata van een document in de sitemap bijgewerkt moet worden. Gebruik dus voor `lastmod` zowel de wijizgingsdatum van het document als van de publicatie. Neem de meest recente wijzigingsdatum.
- In eerste instantie wordt de sitemap bij elke bevraging opnieuw geactualiseerd:
  - Nieuwe documenten worden aan de sitemap toegevoegd.
  - Gewijzigde documenten worden in de sitemap bijgewerkt incl. vermelding van de `lastmod`. 
  - Ingetrokken of verwijderde documenten worden uit de sitemap verwijderd.
- De succesvolle generatie van de sitemap wordt gelogd.
- De (deels) mislukte generatie van de sitemap wordt gelogd incl. de foutmelding(en).

**Comment by felixcicatt** [comment]
@MarcoKlerks De laatste twee acceptatiecriteria gaan over logging. Is het voldoende als dit technische logging is, die niet ontsloten wordt vanuit de applicatie voor eindgebruikers?

**Comment by MarcoKlerks** [comment]
> @MarcoKlerks De laatste twee acceptatiecriteria gaan over logging. Is het voldoende als dit technische logging is, die niet ontsloten wordt vanuit de applicatie voor eindgebruikers?

Dat is prima. De logging is bedoeld voor technisch beheer. Als zij weten waar de logging op de server staat, dan is dat voldoende.

> @MarcoKlerks volgens ons is de publicatie bij een document altijd `gepubliceerd` als het document `gepubliceerd` is. Het lijkt dan ook niet nodig om nog apart te checken of de publicatie `gepubliceerd` is. Klopt dat?

Het is mogelijk dat een document op "gepubliceerd" staat, terwijl de publicatie op "concept" staat. Dit kan door een fout van de ODRC-beheerder of (op termijn) door een fout in een applicatie die gekoppeld is aan het ODRC. Om de kans op een datalek te minimaliseren zou ik toch graag deze extra check erin willen hebben.

**Comment by MarcoKlerks** [comment]
De technische logging kon ik uiteraard niet testen.

In het kader van #23 zal ik maandag en dinsdag nog testen of het toevoegen, intrekken en verwijderen van documenten goed gaat.
