### ISSUE TITLE
ODBP: sitemap endpoints cachen en elke 24 uur actualiseren

### ISSUE THREAD

**Issue by felixcicatt** [GPP-Woo/GPP-burgerportaal#23]
We voorzien dat de Woo-sitemap langzaam is om te genereren. Daarom willen we deze cachen, en minimaal elke 24 uur actualiseren.

**Acceptatiecriteria**
- De sitemap wordt minimaal iedere 24 uur geactualiseerd
- Als de sitemap tussentijds wordt opgevraagd, levert ODBP deze uit de cache

**Specific details**
Voorstel is om hier [Output Cache](https://learn.microsoft.com/en-us/aspnet/core/performance/caching/output?view=aspnetcore-8.0) voor te gebruiken

**Comment by MarcoKlerks** [comment]
Dit pak ik maandag en dinsdag op.

**Comment by MarcoKlerks** [comment]
Ik heb vandaag al nieuwe en gewijzigde registraties kunnen testen. Geen problemen aangetroffen.
